### ISSUE TITLE
Body text contains transparency

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/rtp#39]
This isn't necessarily an issue but it does get picked up by HTML_CodeSniffer for WCAG testing as warnings. We can set the color without transparency to get around this.

```css
html {
   color: rgba(0,0,0,.87)
}
```
